### ISSUE TITLE
Not picking up any messages on a Dell U3419W

### ISSUE THREAD

**Issue by rajbos** [ScriptGod1337/kvm#1]
Hi, found your setup for the MonitorTool Hook trying to find additional options for my Dell U3419W, ran it from the download zip and could not get any messages.
Also downloaded the code (will send in some minor PR's that would help a new user) but also no messages being picked up. Note: also no errors. 

Any idea's on how to find out how to set things up?

## Dell Display Manager version:
![image](https://user-images.githubusercontent.com/6085745/110220473-39022b80-7ec6-11eb-987e-628ceb5b8eab.png)

## Tool output:
![image](https://user-images.githubusercontent.com/6085745/110220546-972f0e80-7ec6-11eb-8996-2d1059dfffbe.png)

I do see the DDM starting up, but don't see any messages (tried Contrast and Brightness settings btw, noticed this version of the DDM has an issue with setting the brightness: it always changes the first monitor and not the second, now to find how to report that back to Dell, if you have an idea about that, would be welcome as well! ).

**Comment by ScriptGod1337** [comment]
Hi @rajbos,

thanks for the feedback :) I just checked in my own and I can see that's working with the latest recent version of Dell Display Manager.

Important is that the Dell Display Manager is started as a sub process of Monitor. If Dell Display Manager is already running it will not be started again and nothing is hooked. Please check if the process tree looks like in this screen short
![image](https://user-images.githubusercontent.com/53829529/110992891-dd78e780-8376-11eb-80ca-1491cd18ba16.png)

**Comment by rajbos** [comment]
Hmmm, not sure what changed, if anything at all. I do see the logs now fly by, with the same command! Thanks for checking 👍
